GestorInventarioEmpresas/ViewModels/LoadHours/CompanyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GestorInventarioEmpresas.ViewModels.LoadHours
{
    public class CompanyViewModel
    {
    }
}

GestorInventarioEmpresas/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestorInventarioEmpresas.BackEnd.DAL;
using GestorInventarioEmpresas.BackEnd.Domain.Entities;

namespace GestorInventarioEmpresas.Controllers
{
   
    public class CompaniesController : BaseController
    {
        private GestorInventarioEmpresasContext db = new GestorInventarioEmpresasContext();

        // GET: Companies
        public ActionResult Index()
        {
            return View(db.Companies.ToList());
        }

        // GET: Companies/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Code, Location")] Company company)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Companies.Add(company);
                    db.SaveChanges();
                    Success("Empresa creada con exito", "Exito");
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Error("Existen códigos duplicados", "Error");
                return View(company);
            }
            return RedirectToAction("Index");
             
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Code, Location")] Company company)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(company).State = EntityState.Modified;
                    db.SaveChanges();
                    Success("Empresa modificada con exito", "Exito");
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Error("Existen códigos duplicados", "Error");
                return View(company);
            }
            return RedirectToAction("Index");
           
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpGet]
        public JsonResult DeleteConfirmed(long id)
        {
            Company company = db.Companies.Find(id);
            db.Companies.Remove(company);
            db.SaveChanges();
            return Json(new { success = false, responseText = "The attached file is not supported." }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestorInventarioEmpresas/Views/Companies/Create.cshtml
@model GestorInventarioEmpresas.BackEnd.Domain.Entities.Company
 
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-border panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Empresa</h3>
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-2">
                        <label style="padding-top: 6px;">(*)</label>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-2">
                        <label style="padding-top: 6px;">(*)</label>
                    </div>
                </div>
                <div class="form-group">
                    <label for="cname" class="control-label col-lg-2">Ubicación</label>
                    <div class="col-lg-6">
                        @Html.EnumDropDownListFor(
                        x => x.Location,
                        new { @class = "form-control" })
                    </div>
                    <div class="col-md-2">

                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-8">
                        <input type="submit" value="Crear" class="btn btn-success" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
 

GestorInventarioEmpresas/Views/Companies/Delete.cshtml
@model GestorInventarioEmpresas.BackEnd.Domain.Entities.Company

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeletedByAdmin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeletedByAdmin)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GestorInventarioEmpresas/Views/Companies/Details.cshtml
@model GestorInventarioEmpresas.BackEnd.Domain.Entities.Company

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeletedByAdmin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeletedByAdmin)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GestorInventarioEmpresas/Views/Companies/Edit.cshtml
@model GestorInventarioEmpresas.BackEnd.Domain.Entities.Company

@{
    ViewBag.Title = "Editar";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="panel panel-border panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Empresa</h3>
    </div>
    <div class="panel-body">
        <div class="form-horizontal">

            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-2">
                        <label style="padding-top: 6px;">(*)</label>
                    </div>
                </div>

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-2">
                        <label style="padding-top: 6px;">(*)</label>
                    </div>
                </div>

                <div class="form-group">
                    <label for="cname" class="control-label col-lg-2">Ubicación</label>
                    <div class="col-lg-6">
                        @Html.EnumDropDownListFor(
                        x => x.Location,
                        new { @class = "form-control" })
                    </div>
                    <div class="col-md-2">

                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Editar" class="btn btn-success" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                }

                <div>
                    @Html.ActionLink("Volver", "Index")
                </div>

                @section Scripts {

<script>
    $(document).ready(function () {
        $('#Code').prop('readonly', true);
    });
                    </script>
                    @Scripts.Render("~/bundles/jqueryval")
                }

GestorInventarioEmpresas/Views/Companies/Index.cshtml
@model IEnumerable<GestorInventarioEmpresas.BackEnd.Domain.Entities.Company>
 
<div class="container">
    <div class="panel panel-border panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">
                Empresas
                <a href="@Url.Action("Create", "Companies")" class="btn btn-primary waves-effect waves-light pull-right">

                    <span>
                        <strong>Agregar</strong>
                    </span>  <i class="fa fa-plus"></i>
                </a>
            </h3>

        </div>
        <div class="panel-body">
            <table class="table  table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Code)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th style="width:30px"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Code)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>

                            <td>

                                <a href="@Url.Action("Edit","Companies", new { id = item.Id })"><i class="fa fa-edit"></i></a>
                              @*  <a href="@Url.Action("Details","Companies", new { id = item.Id })"><i class="fa fa-search"></i></a>*@
                                <a onclick="preguntarEliminacionCompanies(this)" title="Eliminar" data-Id="@item.Id" data-Name="@item.Name"><i class="fa fa-trash"></i></a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section scripts{
<script language="javascript">
            $(document).ready(function () {
            $(".table").DataTable({
                language: {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
                "ordering": true,
    "columnDefs": [ {
"targets": 2,
"orderable": false
} ]
            });
        });
                    function preguntarEliminacionCompanies(element) {

                     swal({
                    title: 'Eliminación',
                      text: "Estas seguro que desea eliminar la empresa:" + $(element).data('name'),
                        type: 'warning',
                            showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Si, eliminarlo!'
                            }, function (isConfirm) {
                                if (isConfirm) {
                                     $.ajax({
                        type: "GET",
                        url: '@Url.Action("DeleteConfirmed")',
                        contentType: "application/json; charset=utf-8",
                        data: { id: $(element).data('id') },
                        dataType: "json"
                                     }).done(function () {
                                         location.reload();
                                     });
                                    $('#showSweetAlert').modal('toggle');
                                    swal.close()
                                } else {
                                    swal.close()
                                }
                            });
                    // The function returns the product of p1 and p2
        }
</script>
}